In [3]:
import re

text = "Hello! How are you? :), I'm feeling good. ;-) What's up? :D, ha ha :-) boat de sut :))"
emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text.lower())

print(emoticons)


[':)', ';-)', ':-)', ':)']


In [1]:
import re

# Search for the first occurrence of the pattern
result = re.search(r'\d+', 'The year 2024 is here')
if result:
    print(f'Found a match: {result.group()}')


Found a match: 2024


In [2]:
import re

# Replace all digits with a hyphen
result = re.sub(r'\d', '-', 'My number is 12345')
print(result)  # Output: My number is -----


My number is -----


In [3]:

# Split string by spaces
result = re.split(r'\s+', 'Split this sentence into words')
print(result)  # Output: ['Split', 'this', 'sentence', 'into', 'words']


['Split', 'this', 'sentence', 'into', 'words']


In [4]:

# Compile the pattern for reuse
pattern = re.compile(r'\d+')
result = pattern.findall('123 456 789')
print(result)  # Output: ['123', '456', '789']


['123', '456', '789']


In [5]:
import re

# Find the first occurrence of a pattern
result = re.search(r'(\d+)', 'The answer is 42')
if result:
    print(f'Found a match: {result.group()}')
    print(f'Match starts at: {result.start()}')
    print(f'Match ends at: {result.end()}')


Found a match: 42
Match starts at: 14
Match ends at: 16


In [6]:
result

<re.Match object; span=(14, 16), match='42'>

In [2]:
import torch
from torch.nn.utils.rnn import pad_sequence

a = torch.ones(25, 300)
b = torch.ones(22, 300)
c = torch.ones(15, 300)
pad_sequence([a, b, c]).size()

torch.Size([25, 3, 300])

In [3]:
a


tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [4]:
b

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [5]:
pad_sequence([a, b, c])

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [4]:
emoticons = [':)', ':(', ':D']
'      '.join(emoticons)  # Result: ":) :( :D"


':)      :(      :D'

In [9]:
x = 787987970879799696987
y = 3.14
z = 110
w = 110
print(hash(x))  # Output: 5
print(hash(y))  # Output: Some hash value for the float
print(hash(z))  # Output: Some hash value for the float
print(hash(w))  # Output: Some hash value for the float

1695504737930059696
322818021289917443
110
110


In [6]:
s = "hello"
print(hash(s))  # Output: Hash value for the string "hello"


2627168912542263326


In [7]:
t = (1, 2, "hello")
print(hash(t))  # Output: Hash value for the tuple


-5955050803291279977
